### GENERAL SETTINGS ###

# Site settings
title: Connor-King
description: "Games development progress and portfolio"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/" #important: start with /
url: "https://github.com/Connor-King/Connor-King.github.io.git"

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: false
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: facebook
    url:
  - title: twitter
    url: https://twitter.com/Connor_King54
  - title: instagram
    url:
  - title: tumblr
    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - 3 High Street,
    - Staple Hill, Bristol, BS16 5HA,
    - United Kingdom.
email: connor.king3131@gmail.com



### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Connor King
    position: Student
    text: Truly passionate gamer and games developer. I am self motivated and enjoy making games.
    img: profile_1.jpg
    social:
      - title: envelope #use for email address
        url: mailto:connor.king3131@gmail.com
      - title: twitter
        url: https://twitter.com/Connor_King54
 
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Coding can be more enjoyable than playing a game... if you like puzzle games."
